<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mailadres_form_fieldsemail</name>
   <tag></tag>
   <elementGuidId>6ec1e469-2248-4115-b624-f84e76421c17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form-field-email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form-field-email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Uw E-mailadres*&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f685e9c-56b5-4d14-ae23-2efb1e3669ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b68f9fae-aa74-4a99-9f3d-4cd10a0f377d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a9fd923b-8ec3-4eeb-bcec-384b2f77c45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_fields[email]</value>
      <webElementGuid>ce0b346b-91ef-45b7-8f0d-2a7d5ab0ff0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-field-email</value>
      <webElementGuid>0aef5236-3023-4ae4-bca8-f539c362071e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-field elementor-size-sm  elementor-field-textual</value>
      <webElementGuid>7eaaeb12-5c8f-44d3-be0d-32d32ea8d8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Uw E-mailadres*</value>
      <webElementGuid>04ff5f82-abf0-495f-a5a6-aa7a9e495aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5ac534b8-c50f-4d13-a802-29dd442d1901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6c5e63b1-e112-4d18-9f1d-bfaacb987cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;page-content&quot;]/div[@class=&quot;elementor elementor-1193&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-214dd5e9 elementor-section-full_width elementor-section-height-min-height elementor-section-items-stretch elementor-section-content-middle elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-no&quot;]/div[@class=&quot;elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-11d01999&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-42b27c1a elementor-button-align-center ha-has-bg-overlay elementor-widget elementor-widget-form&quot;]/div[@class=&quot;elementor-widget-container&quot;]/form[@class=&quot;elementor-form&quot;]/div[@class=&quot;elementor-form-fields-wrapper elementor-labels-&quot;]/div[@class=&quot;elementor-field-type-email elementor-field-group elementor-column elementor-field-group-email elementor-col-50 elementor-field-required&quot;]/input[@id=&quot;form-field-email&quot;]</value>
      <webElementGuid>47473705-668d-44ba-a658-ae7086881882</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form-field-email']</value>
      <webElementGuid>a7f5aab2-dc06-4819-9586-3a3b1a0397e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div/section/div/div[2]/div/div[3]/div/form/div/div[3]/input</value>
      <webElementGuid>bc4de711-82ba-4bca-971b-de0d31ac034a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>b8dfe365-93a2-47ca-9d79-6d5a9c2c2666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'form_fields[email]' and @id = 'form-field-email' and @placeholder = 'Uw E-mailadres*']</value>
      <webElementGuid>00226eb1-45e9-4849-adda-2be30ce5dc49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
