<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Alles aanvaarden</name>
   <tag></tag>
   <elementGuidId>30126033-81c4-420a-95e9-e42fa7de95d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='wt-cli-accept-all-btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wt-cli-accept-all-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Alles aanvaarden&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cf9855b2-5033-4fdc-8e88-77c3d2a1be24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wt-cli-accept-all-btn</value>
      <webElementGuid>be0f45a5-b6e0-40c4-9d97-50e1009435a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea72ec25-8015-4004-b466-cf91d10c1d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cli_action</name>
      <type>Main</type>
      <value>accept_all</value>
      <webElementGuid>49601181-95db-4061-8a02-36a4f992ba92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wt-cli-element medium cli-plugin-button wt-cli-accept-all-btn cookie_action_close_header cli_action_button</value>
      <webElementGuid>62d035c6-308c-47c7-a18e-8f81d458b037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alles aanvaarden</value>
      <webElementGuid>3a304d06-f1b0-4e55-bd8d-ec190eb98ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wt-cli-accept-all-btn&quot;)</value>
      <webElementGuid>f9d37630-dfdc-4159-8d60-8a013b08f15a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='wt-cli-accept-all-btn']</value>
      <webElementGuid>758c375c-253d-4fb8-84aa-5db5b0e67ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookie-law-info-bar']/span/div/div[2]/a[2]</value>
      <webElementGuid>bcb1dd5a-f80b-46dc-8f40-a7c5d3fcc5e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Alles aanvaarden')]</value>
      <webElementGuid>41831710-c321-433b-a684-e8900b8cf193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookie Instellingen'])[1]/following::a[1]</value>
      <webElementGuid>b74cc01d-92ca-444f-b523-91a169e0ba10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='info@m2q.be'])[2]/following::a[2]</value>
      <webElementGuid>11ca9c3b-f3d6-470c-ad63-5f93bcb3ba72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage consent'])[1]/preceding::a[1]</value>
      <webElementGuid>d5c4359b-4b62-4f68-87e2-6bcc7c72e47d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sluiten'])[1]/preceding::a[1]</value>
      <webElementGuid>a2f5739b-6cce-436a-8a91-d8c3164a23de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alles aanvaarden']/parent::*</value>
      <webElementGuid>ba7a9c4d-3d02-42eb-8497-4dfa7cd0921c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>08189257-bdf9-4eef-b994-f776225b8b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'wt-cli-accept-all-btn' and (text() = 'Alles aanvaarden' or . = 'Alles aanvaarden')]</value>
      <webElementGuid>be0a155c-bda5-4810-8f10-5a2ce8be8b06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
