<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_E-mailadres_form_fieldsemail</name>
   <tag></tag>
   <elementGuidId>b4ab355b-9e7c-48c7-b350-a1b3884cae46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form-field-email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form-field-email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Uw E-mailadres*&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0c65803-f854-4375-99d2-d4837d5de4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>44782acb-c1c5-4d6a-8447-52acd194481f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>a8d55f0d-9785-46c8-96b4-68a212820a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_fields[email]</value>
      <webElementGuid>c21d5af8-5b89-4138-b983-6df1fb31ba3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-field-email</value>
      <webElementGuid>2cf1588c-3899-4bcf-b2b9-29925efb8142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-field elementor-size-sm  elementor-field-textual</value>
      <webElementGuid>0be7f974-d580-4c3d-a6ca-93fb45d41337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Uw E-mailadres*</value>
      <webElementGuid>a6818482-e521-431d-9b35-7a130be22927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>65c15d0b-ad5b-41be-a706-41dc1eaa3cbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6feda8e5-3b60-46bb-979b-f25b81684148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;page-content&quot;]/div[@class=&quot;elementor elementor-1193&quot;]/section[@class=&quot;elementor-section elementor-top-section elementor-element elementor-element-214dd5e9 elementor-section-full_width elementor-section-height-min-height elementor-section-items-stretch elementor-section-content-middle elementor-section-height-default&quot;]/div[@class=&quot;elementor-container elementor-column-gap-no&quot;]/div[@class=&quot;elementor-column elementor-col-50 elementor-top-column elementor-element elementor-element-11d01999&quot;]/div[@class=&quot;elementor-widget-wrap elementor-element-populated&quot;]/div[@class=&quot;elementor-element elementor-element-42b27c1a elementor-button-align-center ha-has-bg-overlay elementor-widget elementor-widget-form&quot;]/div[@class=&quot;elementor-widget-container&quot;]/form[@class=&quot;elementor-form&quot;]/div[@class=&quot;elementor-form-fields-wrapper elementor-labels-&quot;]/div[@class=&quot;elementor-field-type-email elementor-field-group elementor-column elementor-field-group-email elementor-col-50 elementor-field-required&quot;]/input[@id=&quot;form-field-email&quot;]</value>
      <webElementGuid>6127b980-362e-4236-a72e-47ad9a2d9fe0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form-field-email']</value>
      <webElementGuid>01706ec4-474e-44bd-bc2e-998a6438ea04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div/section/div/div[2]/div/div[3]/div/form/div/div[3]/input</value>
      <webElementGuid>eeb91b87-3188-4dfe-825d-9c10e520bfc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>3b483e06-7744-40d1-a856-087b90a64636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'form_fields[email]' and @id = 'form-field-email' and @placeholder = 'Uw E-mailadres*']</value>
      <webElementGuid>79cba51b-9b1c-495b-91ff-cafbabe79b11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
