<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Telefoonnummer_form_fieldsfield_13f8176</name>
   <tag></tag>
   <elementGuidId>4bf8d756-144d-4a8e-94ea-db28086a5ea3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form-field-field_13f8176']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form-field-field_13f8176</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Uw telefoonnummer*&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d782dd67-ea17-4b19-9c74-68f24f7b9cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>25fd23bd-62e7-4530-bfef-54a836ea8473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_fields[field_13f8176]</value>
      <webElementGuid>d3497293-52ce-459f-ab49-d7e0dbd3feed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-field-field_13f8176</value>
      <webElementGuid>a92cc45e-173d-4164-ad9c-1bea00f1e482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-field elementor-size-sm  elementor-field-textual</value>
      <webElementGuid>4ddde296-2c92-4047-94d1-fdab11fe6e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Uw telefoonnummer*</value>
      <webElementGuid>bc7c4bc6-7be1-47bd-a842-2211419b11ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e5784b4d-f781-484d-bafb-e44d37a20851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>95648b24-9a2a-4fde-9a58-35430423cecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-field-field_13f8176&quot;)</value>
      <webElementGuid>43851456-1cb5-4cda-9ea8-3c89060703ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form-field-field_13f8176']</value>
      <webElementGuid>628d2157-17f6-49c2-8095-c82cd8a8df64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div/section/div/div[2]/div/div[3]/div/form/div/div[2]/input</value>
      <webElementGuid>1f78de8b-c3a8-4811-a505-4b772b4b1d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e109b58e-219c-4b32-bc0c-a218e470001a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'form_fields[field_13f8176]' and @id = 'form-field-field_13f8176' and @placeholder = 'Uw telefoonnummer*']</value>
      <webElementGuid>cef8ff16-c79b-4edd-9468-6b78fd36d38e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
