<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Uw vraag_form_fieldsfield_8fc8fef</name>
   <tag></tag>
   <elementGuidId>6c5f2101-7547-4a42-8b45-da0fb3392645</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='form-field-field_8fc8fef']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form-field-field_8fc8fef</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Uw vraag&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c81e7ca1-5c5e-40ef-ae3d-ff7619e2d287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>elementor-field-textual elementor-field  elementor-size-sm</value>
      <webElementGuid>035353db-a2b9-4b00-8ab5-32040d3f3b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_fields[field_8fc8fef]</value>
      <webElementGuid>63362bc9-5308-405d-a460-5001d1d2dc39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-field-field_8fc8fef</value>
      <webElementGuid>9ffd7446-2e06-4947-837e-0eb5123b76b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>eccdfa38-e488-4909-975a-0f266cd2ea83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Uw vraag</value>
      <webElementGuid>ad84aeee-4bf1-4be8-8eb2-6678ea4130cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>660e1cbb-d0b3-404e-ba70-78aa81285b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a3c6c244-09ba-4142-88c3-45a983c4f6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-field-field_8fc8fef&quot;)</value>
      <webElementGuid>9662e644-e990-42ee-9cdf-00759dfc7bc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='form-field-field_8fc8fef']</value>
      <webElementGuid>22add06e-4612-4497-abee-30e0391e8acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div/section/div/div[2]/div/div[3]/div/form/div/div[5]/textarea</value>
      <webElementGuid>effbe36f-c5ab-4736-b13d-cbd5adc0ad68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>97a806b2-82b0-46f7-bc25-cd51991b7662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'form_fields[field_8fc8fef]' and @id = 'form-field-field_8fc8fef' and @placeholder = 'Uw vraag']</value>
      <webElementGuid>25ab9bfa-60f6-4263-9d3b-cb8f15ee99c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
